### ISSUE TITLE
Update GitHub repository description and README

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-theme-plone#3]
Repository description

<strike>* [ ] Currently GitHub repository description reads "No description, website, or topics provided." Something like "A Gatsby Theme for Plone CMS" would be better</strike>

README

* [x] Embed build status badge from Travis-CI https://docs.travis-ci.com/user/status-images/
* [ ]Add step-by-step descriptions for creating a Gatsby site project with gatsby-theme-plone, using https://plonedemo.kitconcept.com/en as the source

**Comment by iFlameing** [comment]
@datakurre I don't have permission to edit Repository description. can you give me?

**Comment by iFlameing** [comment]
@datakurre I updated the README.md can you take look?

**Comment by datakurre** [comment]
@iFlameing Sorry about the description. I was unaware that you could lose your rights for that when moving a repository under collective. Neither do I have permission to change that.

About README:

I believe GatsbyJS is still missing documentation for using themes. Maybe we should link the few blog post where they talk about it?

The README is missing, how to change the gatsby-source-plone baseUrl to a custom site. If you don't have other means to test that yet, you could try changing it to https://plonedemo.kitconcept.com/de (the German version of the demo site).

**Comment by iFlameing** [comment]
@datakurre How I can get the access of variable passed as an option in the gatsby-theme-plone plugin configuration. For example 
```javascript 
module.exports = {
    __experimentalThemes: [
        {
            resolve : "gatsby-theme-plone",
            options : {
                baseUrl: 'https://plonedemo.kitconcept.com/en',
            },
        }
    ]
}
```
I want to access the baseUrl variable in gatasby-theme-plone. How I can access it?

**Comment by datakurre** [comment]
@iFlameing I don’t know. That’s something to be asked from gatsby community of checked from existing gatsby theme examples. Maybe search for ”gatsby-theme-” packages...

**Comment by iFlameing** [comment]
@datakurre I think it is similar to what we are doing in gatsby-source-plone. Can you tell me how you are accessing the baseUrl variable in gatsby-source-plone which is passed as plugin options?

**Comment by datakurre** [comment]
@iFlameing 

https://www.gatsbyjs.org/blog/2018-11-11-introducing-gatsby-themes/
> Themes often need to be parameterized for various reasons, such as changing the base url for subsections of a site or applying branding variables. You can do this through the theme options if you define our theme’s gatsby-config as a function that returns an object.

I would interpret this so that "gatsby-config.js" of gatsby-theme-plone should export a function that accepts options object as its only argument. Then it could use options.baseUrl as the value of gatsby-source-plone baseUrl option.

**Comment by iFlameing** [comment]
@datakurre thanks! I got it and tested successfully pushing changes :) And I think it also solves this issue https://github.com/collective/gatsby-theme-plone/issues/5. what do you think?

**Comment by datakurre** [comment]
@iFlameing Yes. Just make sure that the test project sets the baseUrl. Actually, it could even set the German baseUrl to prove that it works :-)

**Comment by iFlameing** [comment]
@datakurre I successfully tested the passing of custom URL with German baseUrl and also with the local plone website hosted at localhost:8000 with the passing of token for the private scope :) Now Going to update the README.md for issue #5.

**Comment by datakurre** [comment]
@iFlameing Please, do one more iteration for the README.

Try to follow the steps by yourself and see do those make sense.

I wrote my own steps with yarn and those were few
https://community.plone.org/t/sneak-peek-into-gatsbyjs-themes-for-plone/8219/1

Some notes

* path-prefix does not make sense in the README example
* README example should contain baseUrl option from the start, because using the theme makes sense only by overriding that
* I believe that react packages are only required once you start shadowing components

**Comment by iFlameing** [comment]
@datakurre I updated the readme.md. Please! take a look.

**Comment by iFlameing** [comment]
@datakurre I update the readme.md now Travis-ci giving me an error about a conflict.
https://travis-ci.org/collective/gatsby-theme-plone/builds/508491443?utm_medium=notification&utm_source=email. How I can resolve this :(

**Comment by datakurre** [comment]
I cleared Travis-CI caches and restarted build.

**Comment by iFlameing** [comment]
@datakurre thanks :) Just one questions only 6 days left for proposal submitting for gsoc. I am thinking that I should start writing a proposal for the gsoc project. Can you tell me what is the project design of Gatsby plone preview so that I can write proper timing deliveries for the project and also this project is not completed yet. what should I do now?

**Comment by datakurre** [comment]
@iFlameing I updated https://community.plone.org/t/gsoc-2019-gatsbyjs-preview-for-plone-gatsby-source-plone-enhancements/7950?u=datakurre description. I believe the idea could be implemented without touching the Python side. For initial implementation it is enough to poll Plone. For eventual implementation the proposed websocket idea could be good enough: gatsby-source-plone could listen to the configured websocket endpoint for add, change, delete notifications for required updates (during GSOC that websocket server could be just a NodeJS mockup; Plone does not have websocket support yet, so Plone integration for that is outside the scope of GSOC idea).

Currently there is no obvious issues to be fixed in gatsby-source-plone. We cannot fix https://github.com/collective/gatsby-source-plone/issues/78 because plone.restapi is still missing required features. This https://github.com/collective/gatsby-source-plone/issues/168 is huge, but I don't know yet, how to best use the new API to fix the issue. If you have time to learn that API I'm open for ideas. I'd love a way to "snapshot" current GatsbyJS types from a working build and then keep using those to avoid errors when e.g. certain type disappears from the built Plone site.

**Comment by iFlameing** [comment]
@datakurre can you make some comment on the proposal. I already share with you . But here is the quick link.https://docs.google.com/document/d/1rJzQZPcQgWAXaBZLW3Rl2pw48SfTAesaNmCmGkn6irg/edit?usp=sharing
